version: "3.9"

services:
  db:
    image: postgres:15
    container_name: imunetrack-db
    restart: always
    environment:
      POSTGRES_USER: imunetrack_user
      POSTGRES_PASSWORD: imunetrack_pass
      POSTGRES_DB: imunetrack
    ports:
      - "5433:5432"
    volumes:
      - imunetrack_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: imunetrack-backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://imunetrack_user:imunetrack_pass@db:5432/imunetrack
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  imunetrack_data:
